name: Internship Scraper Cron

on:
  schedule:
    # 9 AM IST → 3:30 AM UTC
    - cron: "30 3 * * *"
    # 6 PM IST → 12:30 PM UTC
    - cron: "30 12 * * *"
    # Midnight IST → 6:30 PM UTC
    - cron: "30 18 * * *"
  workflow_dispatch:  # allow manual run from Actions tab

jobs:
  ping-flask-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Unified Scraper (/update_all)
        run: |
          echo "🔄 Pinging unified scraper (Internshala + Indeed)..."
          URL="https://internship-bot-bilc.onrender.com/update_all"
          for i in {1..5}; do
            response=$(curl -s -w "\nHTTP_STATUS:%{http_code}\n" "$URL" || true)
            echo "$response"
            status=$(echo "$response" | grep "HTTP_STATUS" | cut -d: -f2)
            if [ "$status" -eq 200 ]; then
              echo "✅ Unified scraper ran successfully."
              exit 0
            fi
            echo "⚠️ Attempt $i failed with status $status. Retrying in 20s..."
            sleep 20
          done
          echo "❌ Unified scraper did not respond after 5 retries."
          exit 1
